---
title: Bò Né 3 Ngon
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Bò Né 3 Ngon
description: 'Nhượng quyền bò né 3 Ngon Hỗ trợ mở quán bò né ở các tỉnh thành phố.tư
  vấn mở quán bò né,cung cấp nguyên liệu làm bò né. Liên hệ: 090 519 96 80.'
logo: "/uploads/chuoi-bo-ne-3-ngon.jpg"
favicon: assets/images/logo.png
baseurl: 
google_analytics: UA-140445892-1
disqus: bone3ngon
mailchimp-list: 
include:
- _pages
permalink: "/:title/"
authors:
  sal:
    name: bo-ne-3-ngon
    display_name: bò né 3 ngon
    gravatar: 4a12c8f549bfeae272fa1e1893dc2c46
    email: 
    web: http://bone3ngon.com.vn
    twitter: https://twitter.com/3ngon
    description: 'Nhượng quyền bò né 3 Ngon Hỗ trợ mở quán bò né ở các tỉnh thành
      phố.tư vấn mở quán bò né,cung cấp nguyên liệu làm bò né. Liên hệ: 090 519 9680.'
  john:
    name: John
    display_name: John
    avatar: assets/images/avatar.png
    gravatar: 4a12c8f549bfeae272fa1e1893dc2c46
    email: 
    web: http://bone3ngon.com.vn
    twitter: https://twitter.com/3ngon
    description: 'Nhượng quyền bò né 3 Ngon Hỗ trợ mở quán bò né ở các tỉnh thành
      phố.tư vấn mở quán bò né,cung cấp nguyên liệu làm bò né. Liên hệ: 090 519 9680.'
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
paginate: 6
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: 1363087678
lazyimages: disabled
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
